spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: auth-server


  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: "123456"
  redis:
    host: 127.0.0.1

server:
  port: 9999


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


security:
  oauth2:
    resource:
      filter-order: 3
