#server:
#  port: 9001

#spring:
#  application:
#    name: service-user
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: "123456"
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#security:
#  oauth2:
#    resource:
#      #是用户终端访问用户信息的URL
#      user-info-uri: http://localhost:8766/uaa/user
#      prefer-token-info: false

spring:
  application:
      name: service-user
  cloud:
    config:
      name: service-user
      profile: dev
      uri: http://127.0.0.1:8888
endpoints:
  refresh:
    enabled: true