server:
  port: 9002
spring:
  application:
    name: service-blog
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.138.229:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: admin
    password: "admin123"
  mybatis:
    configuration:
      cacheEnabled: true
      lazyLoadingEnabled: true
      aggressiveLazyLoading: true
      multipleResultSetsEnabled: true
      useColumnLabel: true
      useGeneratedKeys: false
      autoMappingBehavior: PARTIAL
      defaultExecutorType: REUSE
      mapUnderscoreToCamelCase: true
      localCacheScope: SESSION
      jdbcTypeForNull: NULL
  redis:
    host: 127.0.0.1
    port: 6379
    password: "123456"

mybatis:
  mapperLocations: classpath:mybatis/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/